### PR TITLE
Move connectionset from analyzer

### PR DESCRIPTION
**Pull request by elazarg**
Temporarily this adds a dependency on the synthesizer. It should be changed soon.

### CODE REVIEW

**Review by adisos — COMMENTED** [review]
Should also move `statefuleness` to `models`?

**Comment by elazarg** [comment]
The CI linter required multiple changes to stateful_test for some reason. The command line linter did not warn about most of them.

**Comment by elazarg** [comment]
> Should also move `statefuleness` to `models`?

Done

**Review by adisos — APPROVED** [review]

**Comment by elazarg** [comment]
Moved some parts from synthesis here, and removed the dependency on the synthesis JSON format.

**Comment by elazarg** [comment]
Replaced by #10

**Pull request closed without merging**
